/* tn_hd_pending.js - TDEC "HD Requests Collected" list (Page 2), AUTO-GENERATED by hd_daily_update.py.
   These are HD requests from TDEC's DataViewer that may NOT be on the ArcGIS map service yet
   (or have no coordinates). hd_requests.html overlays any not already shown live, placing
   coordinate-less ones on the county centroid, flagged "location not added".
   sites[] = {id, prop, county, city, loc, lat, lon, ms}  (lat/lon/ms may be null)
   Placeholder contents until the next `run_update` populates it. */
const HD_EXTRA = {
  generatedAt: "(not yet generated - run run_update.cmd)",
  source: "TDEC DataViewer f?p=2005:34340 (HD Requests Collected)",
  sites: []
};
